Part 1
Getting a basing understanding of CSV files and pandas and adding new columns I have added a method 2 for unique identification sorry couldn't get it to work so I had to use an inbuilt function :)

In [107]:
import pandas as pd
dataframe = pd.read_csv("/content/sample_data/california_housing_train.csv")
rows = dataframe.iloc[0:5]
rows2 = dataframe.iloc[-10:]
print(rows)
print(rows2)
dataframe.describe()
uc = dataframe['total_bedrooms'].nunique()
print("\n" + str(uc))
#M2 for unique identification
'''
arr = []
c = 0
for i in range(len(dataframe['total_bedrooms'])):
  if(len(arr) == 0):
    d =1
  else:
    d = len(arr)
  for a in range(d):
    if(len(arr) != 0 and dataframe['total_bedrooms'][i] != arr[a]):
      c = c + 1
      arr.append(dataframe['total_bedrooms'][i])
      break
    elif(len(arr) == 0):
      arr.append(dataframe['total_bedrooms'][i])
      c = 1
print(c)
print(arr)
arr2 = arr.sort()
print(arr2)
'''
arr3 = []
for i in range(len(dataframe['total_bedrooms'])):
  arr3.append(float(dataframe['total_bedrooms'][i])/float(dataframe['population'][i]))

dataframe.insert(9, "total_bedrooms_per_total_rooms", arr3)
print(dataframe)
#Data Filtering
arr4 = []
for i in range(len(dataframe['median_income'])):
  if(dataframe['median_income'][i] > 5):
    arr4.append(dataframe['median_income'][i])
print(arr4)
print(len(arr4))
arr5 = []
arr6 = []
for i in range(len(dataframe['median_income'])):
  if(dataframe['total_rooms'][i] > 10000 and dataframe['median_house_value'][i] < 150000):
    arr5.append(dataframe['total_rooms'][i])
    arr6.append(dataframe['median_house_value'][i])
df2 = pd.DataFrame({"total_rooms":arr5 , "median_house_value":arr6})
print(df2)

dataframe.to_csv('modified_data.csv', index=True)




   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124

Part 2
Basic use of numpy to manipulate arrays and do basic manipulations with them.

Array creation and indexing

In [62]:
import numpy as np
arr = np.arange(21)
#print(arr) to print :)
print(arr[0::2])
#Slicing
arr2 = np.random.randint(10 , 100, size = (5,4))
print(arr2)
#subarray extraction
a = int(input("Enter the x starting coordinate"))
b = int(input("Enter the y starting coordinate"))
c = int(input("Enter the x ending coordinate"))
d = int(input("Enter the y ending coordinate"))
print(arr2[a:(c+1) , b:(d + 1)])



[ 0  2  4  6  8 10 12 14 16 18 20]
[[75 34 28 38]
 [23 64 43 36]
 [61 29 22 46]
 [13 62 27 97]
 [96 58 69 58]]
Enter the x starting coordinate0
Enter the y starting coordinate0
Enter the x ending coordinate1
Enter the y ending coordinate2
[[75 34 28]
 [23 64 43]]


Array manipulation

In [6]:
import numpy as np
#1d array manipulation to 4x5
#M1
arr = np.arange(20)
arr2 = arr.reshape(4,5)
print(arr2)
#M2
#arr3 = np.random.randint(10 , 100, size = (4,5))
#i = 1
#b = 0
#while(i < 21):
  #if(i%5 != 0):
    #arr3[(i - i%5)/5][i%5 - 1] = arr[i]
  #else:
    #arr3[i/5 - 1][0] = arr[i]
  #i = i + 1
#print(arr3)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Flattening a 2d array & Matrix multiplication

In [13]:
import numpy as np
arr = np.random.randint(1 , 10, size = (2,2))
print(arr)
arr2 = arr.flatten()
print(arr2)
#Matrix Multipication
arr3 = np.random.randint(1 , 10, size = (2,2))
print(arr3)
print(np.matmul(arr , arr3))
#M2 - matrix mlriplication
arr4 = np.random.randint(1 , 10, size = (2,2))
for i in range(2):
  sum = 0
  for j in range(2):
    sum = 0
    for k in range(2):
      sum = sum + arr[i][k]*arr3[k][j]
      arr4[i][j] = sum

print(arr4)


[[1 3]
 [2 6]]
[1 3 2 6]
[[9 3]
 [5 9]]
[[24 30]
 [48 60]]
[[24 30]
 [48 60]]


Boolean and Fancy Indexing

In [14]:
import numpy as np
np.random.randint(0, 101, size = (1,50))
arr = np.random.randint(0, 101, size = (1,50))
print(arr)
print(arr[arr > 50])

[[ 6 75 70  6 98 78 79 19 30 96 70 44 20 98 94 75 79 28  1 60 50 65 92 14
  98 66  7 31 21 13 69 60  2  4  7 59 38 77 69 70 55 34 97 84 48 83 35 97
  25 32]]
[75 70 98 78 79 96 70 98 94 75 79 60 65 92 98 66 69 60 59 77 69 70 55 97
 84 83 97]


Statistical Operations

Cheated a bit with transposing the initial array. I dont really know how to take the mean of a column so made it a row to use arr[i] I dont really know how to do arr[][i] and using another for loop would have been too untidy.

In [106]:
import numpy as np
arr = np.array([[ 0,  1,  2,  3,  4],
 [ 5,  6,  7,  8,  9],
 [10, 11, 12, 13, 14]])
arr = arr.transpose()
print(arr)
for i in range(5):
  print("Mean is " + str(np.mean(arr[i])))
  print("Max is " + str(np.max(arr[i])))
  print("Sum is " + str(np.sum(arr[i])))
for j in range(5):
  arr2 = []
  for i in range(3):
    if(arr[j][i] > np.mean(arr[j])):
      arr2.append(arr[j][i])
  print("Required array for column " + str(j + 1) + " is " + str(arr2))


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
Mean is 5.0
Max is 10
Sum is 15
Mean is 6.0
Max is 11
Sum is 18
Mean is 7.0
Max is 12
Sum is 21
Mean is 8.0
Max is 13
Sum is 24
Mean is 9.0
Max is 14
Sum is 27
Required array for column 1 is [10]
Required array for column 2 is [11]
Required array for column 3 is [12]
Required array for column 4 is [13]
Required array for column 5 is [14]


Part 3
ABCs of coding here nothing difficult although I am a little bit suspicious about the last question so I have made a division calcultar(sorts of)
and just put an If statement Sorry if I understod the question wrong.


Fibonacci seqn

In [ ]:
sum = 0
a = 0
b = 1
print(0)
print(1)
while (sum == sum):
  sum = b + a
  a = b
  b = sum
  if(sum > 100):
      break
  print(sum)



0
1
1
2
3
5
8
13
21
34
55
89


Number Text

In [ ]:
for i in range(1 , 51):
  if(i % 3 == 0 and i % 5 != 0):
    print("Fizz")
  elif(i % 5 == 0 and i % 3 != 0):
    print("Buzz")
  elif(i % 3 == 0 and i % 5 == 0):
    print("FizzBuzz")
  else:
    print(i)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


Median Calculator

In [ ]:
a = int(input("Enter the number of elements you want to enter "))
arr = []
for i in range (0 , a):
  arr.append(int(input("Enter the " + str(i + 1) + " number ")))
if(a%2 == 0):
  print(arr[int(a/2 - 1)]/2 + arr[int(a/2)]/2)
if(a%2 != 0):
  print(arr[int((a + 1)/2 - 1)])


Enter the number of elements you want to enter 4
Enter the 1 number 1
Enter the 2 number 2
Enter the 3 number 3
Enter the 4 number 4
2.5


Average Calculator

In [ ]:
a = 0
sum = 0
while(1 == 1):
  a = a + 1
  b = input("Enter the " + str(a) + "Number & enter None *for ending the list ")
  if(b == "None"):
    print(sum / (a - 1))
    break
  c = int(b)
  sum = sum + c



Enter the 1Number & enter None *for ending the list 2
Enter the 2Number & enter None *for ending the list 3
Enter the 3Number & enter None *for ending the list 4
Enter the 4Number & enter None *for ending the list None
3.0


Error Handling

In [ ]:
a = float(input("Enter the first number to divide"))
b = float(input("Enter the second number to divide"))
if(b == 0):
  print("Cannot divide by 0")
else:
  print("The answer is " + str(a/b))

Enter the first number to divide2
Enter the second number to divide3
The answer is 0.6666666666666666


Part 4
Just did what was asked couldn't do the last part

In [81]:
import numpy as np
arr = np.random.randint(1 , 10, size=(2,3,4))
print(arr)
arr2 = np.random.randint(1, 2, size=(2,4,3))
for i in range(4):
  for j in range(3):
    for k in range(2):
      arr2[k][i][j] = arr[k][j][i]
print(arr2)
sum = 0
for j in range(4):
  for i in range(3):
    for k in range(2):
      sum = sum + arr[k][i][j]
print(sum)



[[[1 1 3 7]
  [9 8 8 1]
  [9 6 4 7]]

 [[3 6 5 4]
  [8 5 5 7]
  [6 4 6 3]]]
[[[1 9 9]
  [1 8 6]
  [3 8 4]
  [7 1 7]]

 [[3 8 6]
  [6 5 4]
  [5 5 6]
  [4 7 3]]]
126
